services:
  app:
    image: 'pomidorki:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/$DB_NAME
      SPRING_DATASOURCE_USERNAME: $DB_USER
      SPRING_DATASOURCE_PASSWORD: $DB_PASSWORD
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    ports:
      - "6868:8080"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
